/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.chats.ci_waooooh;

import org.xmlpull.v1.XmlPullParser;

import android.view.View;

public final class R {
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int TextSizeBody=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int TextSizeHeadline=0x7f010004;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int TextSizeInfo=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int metaButtonBarButtonStyle=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int metaButtonBarStyle=0x7f010000;
    }
    public static final class color {
        public static final int black_overlay=0x7f040000;
        public static final int darkbackground=0x7f040008;
        public static final int divider=0x7f040009;
        public static final int green=0x7f04000c;
        public static final int ondarktext=0x7f040005;
        public static final int orange=0x7f04000b;
        public static final int primary=0x7f040001;
        public static final int primarybackground=0x7f040006;
        public static final int primarydark=0x7f040002;
        public static final int primarytext=0x7f040003;
        public static final int red=0x7f04000a;
        public static final int secondarybackground=0x7f040007;
        public static final int secondarytext=0x7f040004;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int bg_des_fraies=0x7f020000;
        public static final int bg_process_one=0x7f020001;
        public static final int bg_process_trois=0x7f020002;
        public static final int bg_process_two=0x7f020003;
        public static final int bg_unsms=0x7f020004;
        public static final int default_bg=0x7f020005;
        public static final int dp_profilone=0x7f020006;
        public static final int es_slidingpane_shadow=0x7f020007;
        public static final int greenstar=0x7f020008;
        public static final int grey=0x7f020009;
        public static final int greybackground=0x7f02000a;
        public static final int ic_launcher=0x7f02000b;
        public static final int icon=0x7f02000c;
        public static final int message_border=0x7f02000d;
        public static final int redstar=0x7f02000e;
        public static final int splash_l=0x7f02000f;
        public static final int stat_sample=0x7f020010;
        public static final int user_logo=0x7f020011;
		public static int stub;
		public static int cb0_h001;
		public static int cb0_h003;
    }
    public static final class id {
        public static final int account=0x7f090018;
        public static final int account_image_wrapper=0x7f090011;
        public static final int addFriend=0x7f090001;
        public static final int anu_button=0x7f090016;
        public static final int btn_accepter=0x7f09001d;
        public static final int btn_continue=0x7f09001c;
        public static final int btn_finPro=0x7f090017;
        public static final int btn_number=0x7f090024;
        public static final int btn_verifCode=0x7f09001e;
        public static final int button_bar=0x7f090015;
        public static final int cancel=0x7f090002;
        public static final int cancel_login=0x7f09000a;
        public static final int cancel_signUp=0x7f09003a;
        public static final int container=0x7f09001b;
        public static final int dummy_button=0x7f09000d;
        public static final int editText1=0x7f09001f;
        public static final int email=0x7f090038;
        public static final int fullscreen_content=0x7f09000b;
        public static final int fullscreen_content_controls=0x7f09000c;
        public static final int hint=0x7f090013;
        public static final int hint_or_warning=0x7f090019;
        public static final int icon=0x7f090003;
        public static final int imageView1=0x7f090027;
        public static final int login=0x7f090009;
        public static final int menu_settings=0x7f09003c;
        public static final int message=0x7f09000f;
        public static final int messageHistory=0x7f09000e;
        public static final int newFriendUsername=0x7f090000;
        public static final int password=0x7f090008;
        public static final int passwordAgain=0x7f090037;
        public static final int progressBar1=0x7f09003b;
        public static final int secondary_hint=0x7f090014;
        public static final int sendMessageButton=0x7f090010;
        public static final int signUp=0x7f090039;
        public static final int start=0x7f090005;
        public static final int stop=0x7f090006;
        public static final int text=0x7f090004;
        public static final int text1=0x7f09001a;
        public static final int textBotom2=0x7f090036;
        public static final int textView16=0x7f09002d;
        public static final int textView17=0x7f09002e;
        public static final int textView18=0x7f09002f;
        public static final int textView2=0x7f090022;
        public static final int textView7=0x7f090031;
        public static final int textView8=0x7f090032;
        public static final int textView88=0x7f090028;
        public static final int textView9=0x7f090033;
        public static final int textView91=0x7f09002c;
        public static final int textView92=0x7f09002a;
        public static final int textView97=0x7f090029;
        public static final int textViewBeforeBotom1=0x7f090034;
        public static final int textViewBotom1=0x7f090035;
        public static final int textViewTitle2=0x7f090030;
        public static final int textViewelse=0x7f09002b;
        public static final int text_des_fraies=0x7f090025;
        public static final int text_deuxcent=0x7f090023;
        public static final int text_signplus=0x7f090021;
        public static final int text_unSms=0x7f090026;
        public static final int text_verifiecode=0x7f090020;
        public static final int userName=0x7f090007;
        public static final int user_photo=0x7f090012;
		public static int thumbnail;
		public static int title;
		public static int rating;
		public static int genre;
		public static int releaseYear;
		public static int list;
		public static int cb0_chat_emoticon_image;
		public static int cb0ChatListviewMsgRight;
		public static int cb0ChatListviewNameRight;
		public static int cb0ChatListviewAvatarRight;
		public static int cb0ChatListviewMsgLeft;
		public static int cb0ChatListviewNameLeft;
		public static int cb0ChatListviewAvatarLeft;
    }
    public static final class layout {
        public static final int add_new_friend=0x7f030000;
        public static final int friend_list_screen=0x7f030001;
        public static final int list_screen=0x7f030002;
        public static final int local_service_controller=0x7f030003;
        public static final int login_screen=0x7f030004;
        public static final int main_layout=0x7f030005;
        public static final int messaging_screen=0x7f030006;
        public static final int modif_profile_layout=0x7f030007;
        public static final int notes_row=0x7f030008;
        public static final int process_one=0x7f030009;
        public static final int process_trois=0x7f03000a;
        public static final int process_two=0x7f03000b;
        public static final int profile_layout=0x7f03000c;
        public static final int sign_up_screen=0x7f03000d;
        public static final int splash=0x7f03000e;
		public static XmlPullParser list_row;
		public static View activity_main;
		public static int cb0_chat_emoticon;
		public static XmlPullParser cb0_chat_listview_item_right;
		public static XmlPullParser cb0_chat_listview_item_left;
    }
    public static final class menu {
        public static final int menu=0x7f080000;
		public static int main;
    }
    public static final class string {
        public static final int OK=0x7f060010;
        public static final int accept=0x7f060093;
        public static final int account_already_exists=0x7f060107;
        public static final int account_details=0x7f060143;
        public static final int account_settings_confirm_password=0x7f0600c2;
        public static final int account_settings_example_jabber_id=0x7f0600c1;
        public static final int account_settings_jabber_id=0x7f0600bf;
        public static final int account_settings_password=0x7f0600c0;
        public static final int account_status_connecting=0x7f0600a8;
        public static final int account_status_disabled=0x7f0600a6;
        public static final int account_status_incompatible_server=0x7f0600b2;
        public static final int account_status_no_internet=0x7f0600ac;
        public static final int account_status_not_found=0x7f0600ab;
        public static final int account_status_offline=0x7f0600a9;
        public static final int account_status_online=0x7f0600a7;
        public static final int account_status_regis_conflict=0x7f0600ae;
        public static final int account_status_regis_fail=0x7f0600ad;
        public static final int account_status_regis_not_sup=0x7f0600b0;
        public static final int account_status_regis_success=0x7f0600af;
        public static final int account_status_security_error=0x7f0600b1;
        public static final int account_status_unauthorized=0x7f0600aa;
        public static final int account_status_unknown=0x7f0600a5;
        public static final int action_accounts=0x7f06002a;
        public static final int action_add=0x7f060029;
        public static final int action_add_account=0x7f06002f;
        public static final int action_add_phone_book=0x7f060031;
        public static final int action_clear_history=0x7f060060;
        public static final int action_contact_details=0x7f06002c;
        public static final int action_delete_contact=0x7f060032;
        public static final int action_edit_contact=0x7f060030;
        public static final int action_edit_subject=0x7f0600f5;
        public static final int action_end_conversation=0x7f06002b;
        public static final int action_muc_details=0x7f06002d;
        public static final int action_secure=0x7f06002e;
        public static final int action_settings=0x7f060005;
        public static final int add=0x7f060021;
        public static final int add_back=0x7f0600f9;
        public static final int add_contact=0x7f06005b;
        public static final int add_new_friend=0x7f06001f;
        public static final int add_phone_book_text=0x7f0600c7;
        public static final int additional_information=0x7f06010a;
        public static final int admin=0x7f060042;
        public static final int also_end_conversation=0x7f060064;
        public static final int app_name=0x7f060000;
        public static final int approve_selected_friends=0x7f060025;
        public static final int are_you_sure_verify_fingerprint=0x7f060167;
        public static final int ask_for_presence_updates=0x7f06009c;
        public static final int attach_choose_picture=0x7f06009d;
        public static final int attach_file=0x7f060059;
        public static final int attach_record_voice=0x7f0600be;
        public static final int attach_take_picture=0x7f06009e;
        public static final int bookmark_already_exists=0x7f0600f3;
        public static final int cancel=0x7f06000b;
        public static final int cancel_transmission=0x7f060161;
        public static final int check_image_filesize=0x7f060136;
        public static final int checking_image=0x7f060133;
        public static final int choose_file=0x7f060159;
        public static final int choose_presence=0x7f060065;
        public static final int clear_conversation_history=0x7f060061;
        public static final int clear_histor_msg=0x7f060062;
        public static final int conference_address=0x7f0600ef;
        public static final int conference_address_example=0x7f0600f0;
        public static final int conference_banned=0x7f06012f;
        public static final int conference_created=0x7f06016e;
        public static final int conference_creation_failed=0x7f06016d;
        public static final int conference_kicked=0x7f060131;
        public static final int conference_members_only=0x7f060130;
        public static final int conference_not_found=0x7f0600f6;
        public static final int conference_requires_password=0x7f060110;
        public static final int conference_with=0x7f06016b;
        public static final int conferences=0x7f0600e6;
        public static final int confirm=0x7f06014b;
        public static final int confirm_password=0x7f0600c3;
        public static final int connect=0x7f060106;
        public static final int contact_added_you=0x7f0600f8;
        public static final int contact_already_exists=0x7f0600ed;
        public static final int contact_has_no_pgp_key=0x7f060075;
        public static final int contact_has_read_up_to_this_point=0x7f0600fa;
        public static final int contact_status_away=0x7f0600ca;
        public static final int contact_status_do_not_disturb=0x7f0600cc;
        public static final int contact_status_extended_away=0x7f0600cb;
        public static final int contact_status_free_to_chat=0x7f0600c9;
        public static final int contact_status_offline=0x7f0600cd;
        public static final int contact_status_online=0x7f0600c8;
        public static final int contacts=0x7f06004d;
        public static final int contacts_have_no_pgp_keys=0x7f060077;
        public static final int conversations_foreground_service=0x7f060155;
        public static final int copy_original_url=0x7f06013a;
        public static final int copy_text=0x7f060138;
        public static final int could_not_verify_fingerprint=0x7f060165;
        public static final int crash_report_message=0x7f060053;
        public static final int crash_report_title=0x7f060052;
        public static final int create=0x7f0600ec;
        public static final int create_contact=0x7f0600e8;
        public static final int decrypt=0x7f0600e5;
        public static final int decryption_failed=0x7f06006d;
        public static final int delete=0x7f06004f;
        public static final int delete_bookmark=0x7f0600f2;
        public static final int delete_contact=0x7f0600ea;
        public static final int delete_fingerprint=0x7f060115;
        public static final int delete_messages=0x7f060063;
        public static final int disable_notifications=0x7f06010c;
        public static final int disable_notifications_for_this_conversation=0x7f06010d;
        public static final int download_file=0x7f06015b;
        public static final int download_image=0x7f06006a;
        public static final int dummy_button=0x7f060001;
        public static final int dummy_content=0x7f060002;
        public static final int edit=0x7f06004e;
        public static final int email=0x7f060018;
        public static final int enable=0x7f06010f;
        public static final int enable_notifications=0x7f06016a;
        public static final int encrypted_image_received=0x7f060079;
        public static final int encrypted_message=0x7f060040;
        public static final int encrypted_message_received=0x7f060078;
        public static final int encryption_choice_none=0x7f0600b3;
        public static final int encryption_choice_otr=0x7f0600b4;
        public static final int encryption_choice_pgp=0x7f0600b5;
        public static final int enter_password=0x7f060111;
        public static final int error=0x7f060094;
        public static final int error_compressing_image=0x7f0600a1;
        public static final int error_decrypting_file=0x7f060092;
        public static final int error_file_not_found=0x7f0600a2;
        public static final int error_io_exception=0x7f0600a3;
        public static final int error_not_an_image_file=0x7f0600a0;
        public static final int error_out_of_memory=0x7f0600c6;
        public static final int error_publish_avatar_converting=0x7f0600ff;
        public static final int error_publish_avatar_no_server_support=0x7f060102;
        public static final int error_publish_avatar_server_reject=0x7f0600fe;
        public static final int error_saving_avatar=0x7f060100;
        public static final int error_security_exception_during_image_copy=0x7f0600a4;
        public static final int exit_application=0x7f060016;
        public static final int failed=0x7f06014e;
        public static final int file=0x7f060160;
        public static final int file_deleted=0x7f060163;
        public static final int file_offered_for_download=0x7f06015f;
        public static final int file_transmission_failed=0x7f060162;
        public static final int fill_both_username_and_password=0x7f060012;
        public static final int finDinsta=0x7f0600fb;
        public static final int finish=0x7f060151;
        public static final int friend_list=0x7f060007;
        public static final int hello=0x7f060006;
        public static final int hello_world=0x7f060004;
        public static final int ignore=0x7f060117;
        public static final int image_file=0x7f06007a;
        public static final int image_file_deleted=0x7f060134;
        public static final int image_offered_for_download=0x7f06006b;
        public static final int image_transmission_failed=0x7f060140;
        public static final int image_url=0x7f06013c;
        public static final int in_progress=0x7f06014c;
        public static final int install=0x7f060071;
        public static final int install_openkeychain=0x7f0600de;
        public static final int invalid_jid=0x7f0600c5;
        public static final int invite_contact=0x7f06004c;
        public static final int join=0x7f0600ee;
        public static final int join_conference=0x7f0600e9;
        public static final int just_now=0x7f06003b;
        public static final int keys=0x7f060099;
        public static final int last_seen_day=0x7f0600db;
        public static final int last_seen_days=0x7f0600dc;
        public static final int last_seen_hour=0x7f0600d9;
        public static final int last_seen_hours=0x7f0600da;
        public static final int last_seen_min=0x7f0600d7;
        public static final int last_seen_mins=0x7f0600d8;
        public static final int last_seen_now=0x7f0600d6;
        public static final int leave=0x7f0600f7;
        public static final int local_service_connected=0x7f06000f;
        public static final int local_service_started=0x7f06000d;
        public static final int local_service_stopped=0x7f06000e;
        public static final int login=0x7f06000a;
        public static final int make_sure_username_and_password_correct=0x7f060013;
        public static final int manually_verify=0x7f060166;
        public static final int message_cannot_be_sent=0x7f060027;
        public static final int message_copied_to_clipboard=0x7f06013f;
        public static final int message_options=0x7f060137;
        public static final int message_text=0x7f06013d;
        public static final int messaging=0x7f06000c;
        public static final int mgmt_account_are_you_sure=0x7f0600bc;
        public static final int mgmt_account_delete=0x7f0600b7;
        public static final int mgmt_account_delete_confirm_text=0x7f0600bd;
        public static final int mgmt_account_disable=0x7f0600b8;
        public static final int mgmt_account_edit=0x7f0600b6;
        public static final int mgmt_account_enable=0x7f0600bb;
        public static final int mgmt_account_publish_avatar=0x7f0600b9;
        public static final int mgmt_account_publish_pgp=0x7f0600ba;
        public static final int minute_ago=0x7f06003c;
        public static final int minutes_ago=0x7f06003d;
        public static final int missing_presence_updates=0x7f060112;
        public static final int missing_public_keys=0x7f0600d5;
        public static final int moderator=0x7f060044;
        public static final int muc_details_conference=0x7f0600ce;
        public static final int muc_details_other_members=0x7f0600cf;
        public static final int never_seen=0x7f0600dd;
        public static final int new_friend_request_exist=0x7f060024;
        public static final int next=0x7f060108;
        public static final int nick_in_use=0x7f060041;
        public static final int no_application_found_to_open_file=0x7f060164;
        public static final int no_conference_server_found=0x7f06016c;
        public static final int no_friend=0x7f060020;
        public static final int no_otr_session_found=0x7f060154;
        public static final int no_pgp_key=0x7f060074;
        public static final int no_pgp_keys=0x7f060076;
        public static final int not_connected_to_network=0x7f060026;
        public static final int not_connected_to_service=0x7f060011;
        public static final int not_connected_try_again=0x7f060135;
        public static final int not_in_roster=0x7f06005a;
        public static final int notifications_disabled=0x7f06010e;
        public static final int offering=0x7f060072;
        public static final int ok=0x7f060051;
        public static final int open_file=0x7f06015c;
        public static final int openkeychain_required=0x7f06006e;
        public static final int openkeychain_required_long=0x7f06006f;
        public static final int openpgp_error=0x7f060091;
        public static final int openpgp_messages_found=0x7f0600e0;
        public static final int or_long_press_for_default=0x7f060101;
        public static final int or_touch_phones=0x7f060147;
        public static final int otr_fingerprint=0x7f0600e3;
        public static final int owner=0x7f060043;
        public static final int participant=0x7f060045;
        public static final int password=0x7f060009;
        public static final int password_again=0x7f060017;
        public static final int passwords_do_not_match=0x7f0600c4;
        public static final int preemptively_grant=0x7f06009f;
        public static final int pref_about_conversations_summary=0x7f060123;
        public static final int pref_about_message=0x7f060124;
        public static final int pref_accept_files=0x7f06007e;
        public static final int pref_accept_files_summary=0x7f06007f;
        public static final int pref_advanced_options=0x7f06008b;
        public static final int pref_conference_name=0x7f06012c;
        public static final int pref_conference_name_summary=0x7f06012d;
        public static final int pref_conference_notifications=0x7f060087;
        public static final int pref_conference_notifications_summary=0x7f060088;
        public static final int pref_confirm_messages=0x7f06008e;
        public static final int pref_confirm_messages_summary=0x7f06008f;
        public static final int pref_dont_save_encrypted=0x7f06011c;
        public static final int pref_dont_save_encrypted_summary=0x7f06011d;
        public static final int pref_enable_legacy_ssl=0x7f06011e;
        public static final int pref_enable_legacy_ssl_summary=0x7f06011f;
        public static final int pref_encryption_settings=0x7f060119;
        public static final int pref_expert_options=0x7f060120;
        public static final int pref_expert_options_other=0x7f06012b;
        public static final int pref_expert_options_summary=0x7f060121;
        public static final int pref_force_encryption=0x7f06011a;
        public static final int pref_force_encryption_summary=0x7f06011b;
        public static final int pref_general=0x7f06007b;
        public static final int pref_grant_presence_updates=0x7f060095;
        public static final int pref_grant_presence_updates_summary=0x7f060096;
        public static final int pref_keep_foreground_service=0x7f060157;
        public static final int pref_keep_foreground_service_summary=0x7f060158;
        public static final int pref_never_send_crash=0x7f06008c;
        public static final int pref_never_send_crash_summary=0x7f06008d;
        public static final int pref_notification_grace_period=0x7f060089;
        public static final int pref_notification_grace_period_summary=0x7f06008a;
        public static final int pref_notification_settings=0x7f060080;
        public static final int pref_notifications=0x7f060081;
        public static final int pref_notifications_summary=0x7f060082;
        public static final int pref_show_dynamic_tags=0x7f060168;
        public static final int pref_show_dynamic_tags_summary=0x7f060169;
        public static final int pref_sound=0x7f060085;
        public static final int pref_sound_summary=0x7f060086;
        public static final int pref_ui_options=0x7f060090;
        public static final int pref_use_indicate_received=0x7f060128;
        public static final int pref_use_indicate_received_summary=0x7f060129;
        public static final int pref_use_larger_font=0x7f060125;
        public static final int pref_use_larger_font_summary=0x7f060126;
        public static final int pref_use_send_button_to_indicate_status=0x7f060127;
        public static final int pref_use_send_button_to_indicate_status_summary=0x7f06012a;
        public static final int pref_vibrate=0x7f060083;
        public static final int pref_vibrate_summary=0x7f060084;
        public static final int pref_xmpp_resource=0x7f06007c;
        public static final int pref_xmpp_resource_summary=0x7f06007d;
        public static final int preparing_file=0x7f06015e;
        public static final int preparing_image=0x7f06005f;
        public static final int private_message=0x7f060103;
        public static final int private_message_to=0x7f060104;
        public static final int problem_connecting_to_account=0x7f060056;
        public static final int problem_connecting_to_accounts=0x7f060057;
        public static final int publish_avatar_explanation=0x7f0600fc;
        public static final int publishing=0x7f0600fd;
        public static final int receive_presence_updates=0x7f06009b;
        public static final int receiving_file=0x7f06015a;
        public static final int receiving_image=0x7f06005e;
        public static final int reception_failed=0x7f0600e1;
        public static final int register_account=0x7f060049;
        public static final int remote_fingerprint=0x7f060145;
        public static final int remove_bookmark_text=0x7f060048;
        public static final int remove_contact_text=0x7f060047;
        public static final int request_now=0x7f060114;
        public static final int request_presence_updates=0x7f060113;
        public static final int request_sent=0x7f060022;
        public static final int reset=0x7f060170;
        public static final int respond=0x7f06014d;
        public static final int restart=0x7f060070;
        public static final int save=0x7f060050;
        public static final int save_as_bookmark=0x7f0600f1;
        public static final int scan=0x7f060146;
        public static final int scan_qr_code=0x7f060141;
        public static final int search=0x7f0600e7;
        public static final int secret_accepted=0x7f06016f;
        public static final int secrets_do_not_match=0x7f06014f;
        public static final int send_again=0x7f06013b;
        public static final int send_failed=0x7f06005c;
        public static final int send_never=0x7f060055;
        public static final int send_now=0x7f060054;
        public static final int send_otr_message=0x7f060067;
        public static final int send_pgp_message=0x7f060068;
        public static final int send_plain_text_message=0x7f060066;
        public static final int send_presence_updates=0x7f06009a;
        public static final int send_private_message_to=0x7f060105;
        public static final int send_rejected=0x7f06005d;
        public static final int send_unencrypted=0x7f06006c;
        public static final int sending=0x7f06003f;
        public static final int sending_file=0x7f06015d;
        public static final int server_info_available=0x7f0600d3;
        public static final int server_info_carbon_messages=0x7f0600d0;
        public static final int server_info_pep=0x7f0600d2;
        public static final int server_info_session_established=0x7f060109;
        public static final int server_info_stream_management=0x7f0600d1;
        public static final int server_info_unavailable=0x7f0600d4;
        public static final int share_image=0x7f060139;
        public static final int share_with=0x7f06004a;
        public static final int shared_secret_hint=0x7f060149;
        public static final int shared_secret_secret=0x7f06014a;
        public static final int show_qr_code=0x7f060142;
        public static final int sign_up=0x7f060015;
        public static final int signup_failed=0x7f06001b;
        public static final int signup_fill_all_fields=0x7f060019;
        public static final int signup_successfull=0x7f06001d;
        public static final int signup_type_same_password_in_password_fields=0x7f06001a;
        public static final int signup_username_crashed=0x7f06001c;
        public static final int skip=0x7f06010b;
        public static final int smp=0x7f060148;
        public static final int smp_requested=0x7f060153;
        public static final int start_conversation=0x7f06004b;
        public static final int subscriptions=0x7f060097;
        public static final int sure_delete_fingerprint=0x7f060116;
        public static final int title_activity_about=0x7f060122;
        public static final int title_activity_choose_contact=0x7f06003a;
        public static final int title_activity_conference_details=0x7f060035;
        public static final int title_activity_contact_details=0x7f060036;
        public static final int title_activity_conversations=0x7f060037;
        public static final int title_activity_manage_accounts=0x7f060033;
        public static final int title_activity_process_one=0x7f060003;
        public static final int title_activity_settings=0x7f060034;
        public static final int title_activity_sharewith=0x7f060038;
        public static final int title_activity_start_conversation=0x7f060039;
        public static final int toast_message_otr_fingerprint=0x7f06012e;
        public static final int touch_to_choose_picture=0x7f060028;
        public static final int touch_to_disable=0x7f060156;
        public static final int touch_to_fix=0x7f060058;
        public static final int try_again=0x7f060150;
        public static final int type_friend_username=0x7f060023;
        public static final int unknown_otr_fingerprint=0x7f0600df;
        public static final int unread_conversations=0x7f06003e;
        public static final int url_copied_to_clipboard=0x7f06013e;
        public static final int user_offline=0x7f060014;
        public static final int username=0x7f060008;
        public static final int username_and_password_length_short=0x7f06001e;
        public static final int using_account=0x7f060132;
        public static final int verified=0x7f060152;
        public static final int verify=0x7f0600e4;
        public static final int verify_otr=0x7f060144;
        public static final int view_contact_details=0x7f0600eb;
        public static final int visitor=0x7f060046;
        public static final int waiting=0x7f060073;
        public static final int without_mutual_presence_updates=0x7f060118;
        public static final int you=0x7f0600f4;
        public static final int your_account=0x7f060098;
        public static final int your_fingerprint=0x7f0600e2;
        public static final int your_nick_has_been_changed=0x7f060069;
		protected static CharSequence verify_code;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.

    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.

    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
        public static final int ButtonBar=0x7f070003;
        public static final int ButtonBarButton=0x7f070004;
        public static final int Divider=0x7f070007;
        public static final int FullscreenActionBarStyle=0x7f070009;
        public static final int FullscreenTheme=0x7f070002;
        public static final int MyWaoooohBar=0x7f070006;
        /**  Creation du theme de la barre d'Action 
         */
        public static final int MycustomBarTheme=0x7f070005;
        public static final int Tag=0x7f070008;
    }
    public static final class styleable {
        /** 
         Declare custom theme attributes that allow changing which styles are
         used for button bars depending on the API level.
         ?android:attr/buttonBarStyle is new as of API 11 so this is
         necessary to support previous API levels.
    
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_metaButtonBarButtonStyle com.chats.ci_waooooh:metaButtonBarButtonStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_metaButtonBarStyle com.chats.ci_waooooh:metaButtonBarStyle}</code></td><td></td></tr>
           </table>
           @see #ButtonBarContainerTheme_metaButtonBarButtonStyle
           @see #ButtonBarContainerTheme_metaButtonBarStyle
         */
        public static final int[] ButtonBarContainerTheme = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.chats.ci_waooooh.R.attr#metaButtonBarButtonStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.chats.ci_waooooh:metaButtonBarButtonStyle
        */
        public static final int ButtonBarContainerTheme_metaButtonBarButtonStyle = 1;
        /**
          <p>This symbol is the offset where the {@link com.chats.ci_waooooh.R.attr#metaButtonBarStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.chats.ci_waooooh:metaButtonBarStyle
        */
        public static final int ButtonBarContainerTheme_metaButtonBarStyle = 0;
    };
}
